Repository Prospero-s/project-pie, pull requests merged in 2025-01, with the labels that each got.

#21 feat(*)/PROSP-82-Connexion-avec-postgres-en-local
  compose.override.yaml
  compose.yaml
  migrations/Version20241117212751.php.old
  migrations/Version20241127224101.php.old
  migrations/Version20241213151754.php
  public/build/.vite/entrypoints.json
Labels: need test, features

#22 feat(*): PRSOP-83 - migration sur Cognito pour l'authentification
  assets/app.jsx
  assets/img/logo/logo-prospero-black.svg
  assets/img/logo/logo-prospero-white.svg
  assets/js/components/common/auth/ProtectedRoute.jsx
  assets/js/components/common/layout/AppLayout.jsx
  assets/js/components/common/layout/AuthLayout.jsx
  assets/js/components/common/menu/DropdownNotification.jsx
  assets/js/components/common/menu/DropdownUser.jsx
  assets/js/components/common/menu/Sidebar.jsx
  assets/js/components/common/redirect/LanguageRedirect.jsx
  assets/js/components/investements/TableInvestments.jsx
  assets/js/components/reset-password/ResetPasswordForm.jsx
  assets/js/components/signin/ForgotPasswordModal.jsx
  assets/js/components/signin/VerificationModal.jsx
  assets/js/components/signup/ConfirmationCodeModal.jsx
  assets/js/context/userContext.tsx
  assets/js/i18n.js
  assets/js/lib/awsConfig.js
  assets/js/lib/polyfills.js
  assets/js/lib/supabaseClient.js
  assets/js/locales/en/investments.json
  assets/js/locales/en/reset-password.json
  assets/js/locales/en/signin.json
  assets/js/locales/fr/investments.json
  assets/js/locales/fr/reset-password.json
  assets/js/locales/fr/signin.json
  assets/js/locales/fr/signup.json
  assets/js/mocks/investements/startupsMock.js
  assets/js/pages/AuthCallback.jsx
  assets/js/pages/ResetPassword.jsx
  assets/js/pages/SignIn.jsx
  assets/js/pages/SignUp.jsx
  assets/js/services/auth/awsAuthService.js
  assets/js/services/reset-password/resetPasswordService.js
  assets/js/services/signin/authService.js
  assets/js/services/signup/authService.js
  config/services.yaml
  package-lock.json
  package.json
  src/Controller/MainController.php
  vite.config.js
Labels: need test, features

#23 config/PRSOP-88-Créer-un-env-example
  .env.example
Labels: documentation, need merge

#25 feat(*): PRSOP-89 - création et connexion de la base test aws
  compose.yaml
  init.sql
  makefile
  pgadmin/servers.json
Labels: features, need merge

#26 feat(creation entreprise): PRSOP-2 - ajout de la création d'entreprise manuelle et automatique
  assets/js/components/investements/AddInvestmentModal.jsx
  assets/js/components/investments/AddEnterpriseModal.jsx
  assets/js/components/investments/TableInvestments.jsx
  assets/js/components/investments/steps/AutomaticEnterpriseForm.jsx
  assets/js/components/investments/steps/EnterpriseDetails.jsx
  assets/js/components/investments/steps/EnterpriseMap.jsx
  assets/js/components/investments/steps/FundingDetailsForm.jsx
  assets/js/components/investments/steps/ManualEnterpriseForm.jsx
  assets/js/components/investments/steps/SelectCreationType.jsx
  assets/js/locales/en/investments.json
  assets/js/locales/fr/investments.json
  assets/js/pages/Investments.jsx
  assets/js/services/enterprise/enterpriseService.js
  composer.json
  composer.lock
  config/bootstrap.php
  config/bundles.php
  config/packages/doctrine.yaml
  config/packages/monolog.yaml
  config/services.yaml
  makefile
  migrations/.gitignore
  migrations/Version20250114170754.php
  package-lock.json
  package.json
  src/Controller/.gitignore
  src/Controller/Api/EnterpriseController.php
  src/Controller/Front/MainController.php
  src/Controller/Test/HealthController.php
  src/Entity/.gitignore
  src/Entity/Address.php
  src/Entity/Enterprise.php
  src/Entity/Investment.php
  src/Entity/Representative.php
  src/Repository/.gitignore
  src/Repository/EnterpriseRepository.php
  src/Service/Enterprise/Api/EnterpriseApiClient.php
  src/Service/Enterprise/Api/EnterpriseApiClientInterface.php
  src/Service/Enterprise/Data/EnterpriseDataAggregator.php
  src/Service/Enterprise/Data/EnterpriseDataAggregatorInterface.php
  src/Service/Enterprise/EnterpriseDataAggregator.php
  src/Service/Enterprise/EnterpriseService.php
  src/Service/Enterprise/EnterpriseServiceInterface.php
  src/Service/Enterprise/Scraper/EnterpriseScraperInterface.php
  src/Service/Enterprise/Scraper/InpiEnterpriseScraper.php
  src/Service/Enterprise/Scraper/PappersEnterpriseScraper.php
  src/Service/Enterprise/Scraper/SocieteEnterpriseScraper.php
  symfony.lock
  tailwind.config.js
Labels: wip, features
