Repository Prospero-s/project-pie, pull requests merged in 2025-02, with the labels that each got.

#34 feat/PROSP-31-Data-visualisation-des-startups-2
  assets/app.jsx
  assets/js/components/companies/TableCompanies.jsx
  assets/js/components/companyDetails/InvestmentChart.jsx
  assets/js/components/dashboard/InvestmentGlobalChart.jsx
  assets/js/components/dashboard/InvestmentGlobalFundingChart.jsx
  assets/js/components/dashboard/InvestmentGlobalSectorChart.jsx
  assets/js/components/graphes/BarChart.jsx
  assets/js/components/graphes/DonutChart.jsx
  assets/js/components/graphes/LineChart.jsx
  assets/js/components/graphes/PieChart.jsx
  assets/js/components/investments/TableInvestments.jsx
  assets/js/components/ui/card.jsx
  assets/js/components/ui/chart.jsx
  assets/js/i18n.js
  assets/js/lib/utils.js
  assets/js/locales/en/charts.json
  assets/js/locales/fr/charts.json
  assets/js/pages/CompanyDetails.jsx
  assets/js/pages/Dashboard.jsx
  assets/js/services/company/companyService.js
  assets/js/services/graphe/grapheService.js
  assets/js/services/investment/investmentService.js
  package-lock.json
  package.json
  src/Controller/Api/CompanyController.php
  src/Controller/Api/CompanyInvestmentController.php
  src/Controller/Api/InvestmentController.php
  src/Repository/CompanyInvestmentRepository.php
Labels: features, need merge, feedbacks

#35 feat/PRSOP-29-affichage-des-graphiques-de-données-financières
  assets/js/components/companyDetails/metrics/AllMetrics.jsx
  assets/js/components/companyDetails/metrics/GlobalMetrics.jsx
  assets/js/components/companyDetails/metrics/InvestmentChart.jsx
  assets/js/components/companyDetails/metrics/InvestmentDetails.jsx
  assets/js/components/documents/TableDocuments.jsx
  assets/js/components/graphes/AreaChartInteractiveComponent.jsx
  assets/js/components/graphes/BarChartMixedComponent.jsx
  assets/js/components/graphes/LineChartLabel.jsx
  assets/js/components/graphes/RadarChartComponent.jsx
  assets/js/components/investments/steps/CompanyMap.jsx
  assets/js/i18n.js
  assets/js/locales/en/metrics.json
  assets/js/locales/fr/investments.json
  assets/js/locales/fr/metrics.json
  assets/js/pages/CompanyDetails.jsx
  assets/js/pages/Dashboard.jsx
  assets/js/pages/TextractResults.jsx
  assets/js/services/textract/textractService.js
  package-lock.json
Labels: fix, features, need merge

#36 feat(*): PRSOP-92 - récupération des données d'investissement du groupe pour les graphes + amélioration du design
  assets/js/components/common/field/PasswordStrengthField.jsx
  assets/js/components/common/layout/AppLayout.jsx
  assets/js/components/common/menu/DropdownNotification.jsx
  assets/js/components/companies/TableCompanies.jsx
  assets/js/components/dashboard/InvestmentGlobalChart.jsx
  assets/js/components/dashboard/InvestmentGlobalFundingChart.jsx
  assets/js/components/dashboard/InvestmentGlobalSectorChart.jsx
  assets/js/components/documents/EmptyDocumentState.jsx
  assets/js/components/documents/TableDocuments.jsx
  assets/js/components/graphes/BarChart.jsx
  assets/js/components/graphes/DonutChart.jsx
  assets/js/components/graphes/PieChart.jsx
  assets/js/components/investments/TableInvestments.jsx
  assets/js/components/signup/SignUpButton.jsx
  assets/js/components/signup/SignUpForm.jsx
  assets/js/components/signup/SignUpLink.jsx
  assets/js/components/ui/card.jsx
  assets/js/locales/en/allCompanies.json
  assets/js/locales/en/documents.json
  assets/js/locales/en/investments.json
  assets/js/locales/fr/allCompanies.json
  assets/js/locales/fr/documents.json
  assets/js/locales/fr/investments.json
  assets/js/pages/Dashboard.jsx
  assets/js/pages/Documents.jsx
  assets/js/pages/GroupSelection.jsx
  assets/js/pages/Investments.jsx
  assets/js/pages/SignUp.jsx
  migrations/Version20250117153811.php
  migrations/Version20250121112150.php
  migrations/Version20250128193100.php
  migrations/Version20250203141750.php
  migrations/Version20250203153247.php
  migrations/Version20250205215438.php
  src/Controller/Api/CompanyInvestmentController.php
  src/Entity/CompanyInvestment.php
  src/Repository/CompanyInvestmentRepository.php
  src/Repository/CompanyRepository.php
Labels: fix, need test

#39 feat/PROS-94-mettre-en-place-phpstan-pour-la-qualite-de-code
  .github/workflows/back-check.yml
  .github/workflows/ci.yml
  .gitignore
  assets/js/pages/TextractResults.jsx
  composer.json
  composer.lock
  config/bootstrap.php
  config/preload.php
  makefile
  phpcs.xml.dist
  phpstan.dist.neon
  public/index.php
  src/Controller/Api/CompanyController.php
  src/Controller/Api/CompanyInvestmentController.php
  src/Controller/Api/GroupInvitationController.php
  src/Controller/Api/KpiDataController.php
  src/Controller/Api/TextractController.php
  src/Controller/Api/UserGroupController.php
  src/Controller/Front/MainController.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Company.php
  src/Entity/CompanyAddress.php
  src/Entity/CompanyInvestment.php
  src/Entity/GroupInvitation.php
  src/Entity/GroupRole.php
  src/Entity/UploadDocument.php
  src/Entity/User.php
  src/Entity/UserGroup.php
  src/Enum/KpiStatus.php
  src/Repository/CompanyInvestmentRepository.php
  src/Repository/CompanyRepository.php
  src/Repository/GroupInvitationRepository.php
  src/Repository/GroupRoleRepository.php
  src/Repository/KpiDataRepository.php
  src/Repository/UserGroupRepository.php
  src/Repository/UserRepository.php
  src/Service/AwsTextractService.php
  src/Service/Company/Api/CompanyApiClient.php
  src/Service/Company/Api/CompanyApiClientInterface.php
  src/Service/Company/CompanyDataAggregator.php
  src/Service/Company/CompanyService.php
  src/Service/Company/CompanyServiceInterface.php
  src/Service/Company/Data/CompanyDataAggregator.php
  src/Service/Company/Data/CompanyDataAggregatorInterface.php
  src/Service/Company/Scraper/CompanyScraperInterface.php
  src/Service/Company/Scraper/InpiCompanyScraper.php
  src/Service/Company/Scraper/PappersCompanyScraper.php
  src/Service/Company/Scraper/SocieteCompanyScraper.php
  src/Service/User/UserService.php
  symfony.lock
Labels: fix, features, need merge

#42 feat/PROS-96-verification-traductions-pre-commit
  git-hooks/commit-msg
  git-hooks/pre-commit
  git-hooks/pre-push
  makefile
  scripts/install-hooks.sh
Labels: documentation, features, need merge
