Repository Prospero-s/project-pie, pull requests merged in 2025-04, with the labels that each got.

#46 feat/PROS-98-confirmation-inscription
  assets/app.jsx
  assets/img/logo/logo-icon-prospero-white.png
  assets/js/components/common/field/PasswordStrengthField.jsx
  assets/js/components/common/layout/AppLayout.jsx
  assets/js/components/common/notification/NotifAlert.jsx
  assets/js/components/common/redirect/GroupRedirect.jsx
  assets/js/components/signin/ForgotPasswordModal.jsx
  assets/js/components/signup/ConfirmationCodeModal.jsx
  assets/js/components/signup/SignUpButton.jsx
  assets/js/components/signup/SignUpForm.jsx
  assets/js/context/userContext.tsx
  assets/js/locales/en/signin.json
  assets/js/locales/en/signup.json
  assets/js/locales/fr/signin.json
  assets/js/locales/fr/signup.json
  assets/js/pages/AuthCallback.jsx
  assets/js/pages/Dashboard.jsx
  assets/js/pages/GroupSelection.jsx
  assets/js/pages/SignIn.jsx
  assets/js/pages/SignUp.jsx
  assets/js/services/auth/authCallbackService.js
  assets/js/services/auth/awsAuthService.js
  compose.yaml
  composer.json
  composer.lock
  config/packages/mailer.yaml
  config/services.yaml
  migrations/Version20250317175958.php
  package-lock.json
  package.json
  src/Controller/Api/AuthController.php
  src/Entity/VerificationCode.php
  src/Repository/VerificationCodeRepository.php
  src/Service/Mail/MailService.php
  src/Service/User/AwsCognitoService.php
  symfony.lock
  templates/emails/password_reset.html.twig
  templates/emails/verification.html.twig
  templates/emails/welcome.html.twig
Labels: fix

#45 feat/PROS-45-notifications
  .github/workflows/back-check.yml
  .github/workflows/ci.yml
  .github/workflows/front-check.yml
  README.md
  assets/js/components/common/menu/DropdownNotification.jsx
  assets/js/components/common/menu/Header.jsx
  assets/js/components/investments/TableInvestments.jsx
  assets/js/components/settings/SettingsModal.jsx
  assets/js/components/settings/modals/InviteMemberModal.jsx
  assets/js/components/settings/sections/Preferences.jsx
  assets/js/locales/en/documents.json
  assets/js/locales/en/menu.json
  assets/js/locales/en/settings.json
  assets/js/locales/fr/documents.json
  assets/js/locales/fr/menu.json
  assets/js/locales/fr/settings.json
  assets/js/pages/AuthCallback.jsx
  assets/js/pages/Investments.jsx
  assets/js/pages/TextractResults.jsx
  assets/js/services/notification/notificationService.js
  migrations/Version20250316022042.php
  migrations/Version20250318171914.php
  migrations/Version20250318175809.php
  src/Controller/Api/KpiDataController.php
  src/Controller/Api/NotificationController.php
  src/Controller/Api/NotificationSettingsController.php
  src/Entity/NotificationSettings.php
  src/Entity/Notifications.php
  src/Entity/User.php
  src/Entity/UserNotifications.php
  src/Enum/NotificationStatus.php
  src/Enum/NotificationType.php
  src/Repository/NotificationSettingsRepository.php
  src/Repository/NotificationsRepository.php
  src/Repository/UserNotificationsRepository.php
Labels: features, need merge

#57 fix(migration): correction sur une migration des notifications
  migrations/Version20250316022042.php
Labels: fix, need test
